scan_filter_chain:

- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -0.785
    upper_angle: 0.785
    
#- name: range
#  type: laser_filters/LaserScanRangeFilter
#  params:
#    use_message_range_limits: false
#    lower_threshold: 0.3
#    upper_threshold: .inf
#    lower_replacement_value: -.inf
#    upper_replacement_value: .inf
#- name: intensity
#  type: laser_filters/LaserScanIntensityFilter
#  params:
#    lower_threshold: 8000
#    upper_threshold: 100000
#    disp_histogram: 0
#- name: interpolation
#  type: laser_filters/InterpolationFilter

#- name: shadows
#  type: laser_filters/ScanShadowsFilter
#  params:
#    min_angle: 10
#    max_angle: 170
#    neighbors: 20
#    window: 1
